/*
 * setDescarga.h
 *
 *  Created on: Feb 20, 2018
 *      Author: Luciano
 */

#ifndef FIRMWARE_V2_MASTER_PROJECTS_DISPENSER_INC_SETDESCARGA_H_
#define FIRMWARE_V2_MASTER_PROJECTS_DISPENSER_INC_SETDESCARGA_H_





#endif /* FIRMWARE_V2_MASTER_PROJECTS_DISPENSER_INC_SETDESCARGA_H_ */
